### ISSUE TITLE
Display of mentions and notifications mangled sometimes

### ISSUE THREAD

**Issue by audunmb** [elk-zone/elk#2889]
This only occurs sometimes, and a reload of the page usually fixes the issue. What happens is that my notifications are mangled so that some posts are displayed as being part of just one post. 

Like this: 
![elk-mangled notifications](https://github.com/elk-zone/elk/assets/32357781/139b1a89-af39-405b-a654-3294523010fe)

The picture shows a Favorite notification with the text of three different posts displayed as one post.

**Comment by johnsonm** [comment]
Looks to me a lot like #2216 

That had stopped happening to me some time ago, and honestly I forgot that it was still open. Looks like it might have been fixed at some point without reference to that issue and now started happening again?

**Comment by audunmb** [comment]
Yes this is a duplicate, but didn't find the other issue since I searched for notification issues.

**Comment by johnsonm** [comment]
Yup, I was just linking them together for more information for developers, not complaining about duplication. Issue search is hard. :)

**Comment by Baralheia** [comment]
I'm also seeing this issue, and have for quite some time... at least the last several months. Like the OP, refreshing usually fixes it. I'm using Firefox 128 on Linux Mint 22, but this issue persists across browser versions and across OSs too.

![image](https://github.com/user-attachments/assets/697487cd-7b7f-47a1-abad-c574b41b015a)

**Comment by piebob** [comment]
this is a weird example of the jumbling issue--the mentioned usernames from one notification item were replaced by the mentions from another notification item: 
![image](https://github.com/user-attachments/assets/252e5c08-b944-4328-a632-49d54d72b5cc)

the second notification item has the correct content and mentioned users. the first one has pulled tags from a different post i made. super weird.
