### ISSUE TITLE
Feature request: Specify instance name for local instance installs and have instance lifecycle events supported

### ISSUE THREAD

**Issue by supernovae** [elk-zone/elk#953]
Ask:

Specify instance name for local instance installs and have web experience feel native to that instance.

For example, I have an instance running at https://elk.universeodon.com - If you try and login, it asks for an instance name - if i specify one, it should bypass and just ask to login or authorize the app to Universeodon.com or register on universeodon.com.

Additionally, if this local instance name is provided, there should be links to login/register to the default instance.  

When you set it to a default instance, it would be nice if the default routes matched that of mastodon - without the /servername.com/ - this will help people not confuse googlebot if they impelement this as a front end.

It would also be nice if there was a place for instance notifications to be supported so if I create a notification, there is a flashing bell or something for local instance notifications.  It's built into the standard UI now, but not very visibly ;)

![image](https://user-images.githubusercontent.com/1461719/211678029-e7502dff-ec11-42d1-9e75-56b5c2837087.png)

Eventually, it would be nice if i could just set my theme and have it load elk, but that can be saved for later ;)

**Comment by masto** [comment]
I think a "single instance" or "private instance" flag would be very useful. Pretty sure that's what the comment above is referring to, so I'm leaving this here rather than opening a separate FR. A few reasons why:

* Small/personal instances may not have the resources to support more users
* I want to feel free to modify/break/shut down my deployment at any time without worrying that other people are using it
* Want to avoid any liability for what third parties may do with it

**Comment by DataDrivenMD** [comment]
Any progress on this front? I'm about to install Elk on my instance, and would happily add my address to the GH page and evangelizing Elk to my followers, but I don't feel comfortable doing that for all the reasons you've mentioned, here: 

> * Small/personal instances may not have the resources to support more users
> * I want to feel free to modify/break/shut down my deployment at any time without worrying that other people are using it
> * Want to avoid any liability for what third parties may do with it

**Comment by userquin** [comment]
We need to address a few things:
- multi account is not the same as muti server: we can have multiple accounts in the same server, and so, multi account shouldn't be disabled
- we need to redo the sign in button, forcing to show accounts
- the default server will act as the single instance backend
- review push notifications: maybe we only need to review some mesaages

I'll give it a try tmr.
-

**Comment by danielroe** [comment]
resolved in https://github.com/elk-zone/elk/pull/1606 🎉

**Comment by masto** [comment]
I'm having trouble figuring out how to turn this on. I've updated my deployment to 0.7.3 and tried setting the environment variable SINGLE_INSTANCE_SERVER (and NUXT_SINGLE_INSTANCE_SERVER) to `true`, but I still get the same login experience where I'm asked to type in an arbitrary server name.

Am I misunderstanding what this does? I thought it would restrict usage to just my server.

**Comment by supernovae** [comment]
I think you need to run nightly build to get this feature or wait until .8 or a newer .7 is released

**Comment by userquin** [comment]
Setting `NUXT_SINGLE_INSTANCE_SERVER=true`  and building Elk will not show the popup dialog to request the server, you will be only able to sign-in only to your default server.

All account pages will not use the default server in the browser address.

**Comment by masto** [comment]
@supernovae It's in the release notes for 0.7.3: https://github.com/elk-zone/elk/releases/tag/v0.7.3

I'm probably doing something wrong, but I thought it would be as simple as adding a new environment variable in Netlify and triggering a new deployment. I still get the popup on https://elk.masto.com, though.

**Comment by userquin** [comment]
have you deployed your instance before? if so, you will need to wait Update Elk prompt...

**Comment by userquin** [comment]
upps, not working, maybe nuxt 3.2 update, I'll ping Daniel

**Comment by userquin** [comment]
OK, the environment variable is `NUXT_PUBLIC_SINGLE_INSTANCE`, we've changed the name, you can check it in `.env.example` file

**Comment by masto** [comment]
It's working, thank you for pointing out the correct name. I see it is also in the [docs](https://docs.elk.zone/docs/deployment/netlify) and I should have checked there. I only looked at pr #1606 and didn't consider that there were more commits after that affecting this feature.

Sorry for the noise but hopefully anyone else making the same mistake as me will see it here.
